### ISSUE TITLE
Issue opening blender

### ISSUE THREAD

**Issue by Saleca** [Tintedfireglass/blender-android#1]
Out of all i saw, your solution was the simplest, but i cant open blender.

```
root@localhost:~# blender
Color management: using fallback mode for management
Color management: Error could not find role data role.
Unable to open a display
Aborted
```

can you elaborate your read me to include a fix for this?

thanks

**Comment by Tintedfireglass** [comment]
> Out of all i saw, your solution was the simplest, but i cant open blender.
> 
> ```
> root@localhost:~# blender
> Color management: using fallback mode for management
> Color management: Error could not find role data role.
> Unable to open a display
> Aborted
> ```
> 
> can you elaborate your read me to include a fix for this?
> 
> thanks

hm.... this error commonly comes up when you try to render it in eevee rendering engine as eevee needs to have a display connected for it to work.
could you please give info about which blender version is it? Because I'm not able to reproduce the error
thanks
I'm looking into it.


P. S. if you have any issues I've also made a yt tutorial of this 
https://www.youtube.com/watch?v=rlKfJgDJmBI




Edit :
I figured it. 
typing blender just opens the viewport of blender which doesn't exist. You can only render using this script in cycles. I am working on a simple script to get viewport working too but it's taking time. 
:)

**Comment by Saleca** [comment]
Oh I see, I was watching now the video and noticed you didn't open blender viewport.
I have a Samsung s7+ with keyboard and mouse was hoping to get fully featured blender on the machine.. for small projects should be capable but they dont have android version by default.. its a shame. 
I though this would be something like blender 2.6, like I had on my raspberry pi, but is 3.0
thanks for your help

**Comment by Tintedfireglass** [comment]
> Oh I see, I was watching now the video and noticed you didn't open blender viewport. I have a Samsung s7+ with keyboard and mouse was hoping to get fully featured blender on the machine.. for small projects should be capable but they dont have android version by default.. its a shame. I though this would be something like blender 2.6, like I had on my raspberry pi, but is 3.0 thanks for your help

Yeah, you need to use a VNC viewer like tigereVNC to open the viewport.
Just install tigervnc on both termux and your android and connect them.
